#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

VNTS_user="$vnts_admin_username"
VNTS_pass="$vnts_admin_password"
VNTS_port="$vnts_app_port"
VNTS_token="$vnts_enable_token"
VNTS_cmd="$vnts_white_token"
VNTS_log="$vnts_enable_log"
CONFIG_DIR="${TRIM_DATA_SHARE_PATHS%%:*}"

# vnts的启动命令 
CMD="${TRIM_APPDEST}/bin/vnts "
[ -z "$VNTS_user" ] || CMD="${CMD} -U ${VNTS_user}"
[ -z "$VNTS_pass" ] || CMD="${CMD} -W ${VNTS_pass}"
[ -z "$VNTS_port" ] || CMD="${CMD} -p ${VNTS_port}"
[ "$VNTS_token" = "true" ] || CMD="${CMD} --disable-group-list"
[ -z "$VNTS_cmd" ] || CMD="${CMD} ${VNTS_cmd}"
[ "$VNTS_log" = "true" ] && CMD="${CMD} -l console"

log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')]: INFO $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    # 启动前清空日志文件
    > ${LOG_FILE}
    
    log_msg "开始运行 ..."
    mkdir -p "${CONFIG_DIR}/vnts_wg"
    [ -L "${TRIM_APPDEST}/bin/vnts_wg" ] || ln -sf "${CONFIG_DIR}/vnts_wg" "${TRIM_APPDEST}/bin/vnts_wg"
    [ -L "${CONFIG_DIR}/vnts.log" ] || ln -sf "${LOG_FILE}" "${CONFIG_DIR}/vnts.log"
    # 运行启动参数
    bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
    # 写入进程文件
    printf "%s" "$!" > ${PID_FILE}
    log_msg "启动命令： ${CMD}"
    log_msg "进程PID： $!"
    return 0
}

stop_process() {
    log_msg "正在停止 ..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        
        log_msg "进程PID：${pid}"
        if ! check_process "${pid}"; then
            # 进程不存在，删除进程文件
            rm -f "${PID_FILE}"
            log_msg "进程不存在，删除进程文件"
            return
        fi

        log_msg "发送 TERM signal 停止信号到 PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "等待进程终止... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "发送 KILL signal 强制停止信号到 PID:${pid}..."
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
        else
            log_msg "vnts进程已结束运行！"
        fi
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # 进程在运行中
    else
        return 1  # 进程未运行
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # 进程未运行，但pid文件存在 - 应该要删除它
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # 启动应用的命令，成功返回 0，失败返回 1
    start_process
    ;;
stop)
    # 停止应用的命令，成功返回 0，失败返回 1
    stop_process
    ;;
status)
    # 检查应用运行状态，运行中返回 0，未运行返回 3
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
