#!/bin/bash

### This script is called after the user uninstalls the application.

LOG_FILE="${TRIM_PKGVAR}/info.log"

log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')]: INFO $1" >> ${LOG_FILE}
}

# 获取VNTS的WG客户端数据目录
VNTS_CONFIG_DIR="${TRIM_DATA_SHARE_PATHS%%:*}/vnts_wg"

log_msg "正在卸载，用户选择WG客户端数据保留选项: $vnts_data_action"

# 根据用户选择执行相应逻辑
if [ "$vnts_data_action" = "delete" ]; then
    log_msg "已删除VNTS的WG客户端数据目录：$VNTS_CONFIG_DIR"
    rm -rf ${VNTS_CONFIG_DIR}
else
    log_msg "已保留VNTS的WG客户端数据"
fi

exit 0